<?php

use yii\db\Schema;
use yii\db\Migration;

class m190226_142325_auth_itemDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%auth_item}}',
                           ["name", "type", "description", "rule_name", "data", "created_at", "updated_at"],
                            [
    [
        'name' => 'admin',
        'type' => '1',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createCartridge',
        'type' => '2',
        'description' => 'Создание картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createCartridgeLoading',
        'type' => '2',
        'description' => 'Создание заправок Картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createCartridgeModels',
        'type' => '2',
        'description' => 'Создание моделей карттриджей',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createInventory',
        'type' => '2',
        'description' => 'Создание Инвентарных номеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createLoading',
        'type' => '2',
        'description' => 'Создание заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createLoadingReport',
        'type' => '2',
        'description' => 'Создание отчетов заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createOrder',
        'type' => '2',
        'description' => 'Создание заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createPrinter',
        'type' => '2',
        'description' => 'Создание картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createPrinterCartridgeCompatiblity',
        'type' => '2',
        'description' => 'Создание совместимости моделей картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createPrinterModels',
        'type' => '2',
        'description' => 'Создание моделей принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'createUserOrder',
        'type' => '2',
        'description' => 'Создание заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteCartridge',
        'type' => '2',
        'description' => 'Удаление картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteCartridgeLoading',
        'type' => '2',
        'description' => 'Удаление заправок Картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteCartridgeModels',
        'type' => '2',
        'description' => 'Удаление моделей карттриджей',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteInventory',
        'type' => '2',
        'description' => 'Удаление Инвентарных номеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteLoading',
        'type' => '2',
        'description' => 'Удаление заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteLoadingReport',
        'type' => '2',
        'description' => 'Удаление отчетов заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteOrder',
        'type' => '2',
        'description' => 'Удаление заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deletePrinter',
        'type' => '2',
        'description' => 'Удаление картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deletePrinterCartridgeCompatiblity',
        'type' => '2',
        'description' => 'Удаление совместимости моделей картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deletePrinterModels',
        'type' => '2',
        'description' => 'Удаление моделей принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'deleteUserOrder',
        'type' => '2',
        'description' => 'Удаление заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateCartridge',
        'type' => '2',
        'description' => 'Обновление картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateCartridgeLoading',
        'type' => '2',
        'description' => 'Обновление заправок Картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateCartridgeModels',
        'type' => '2',
        'description' => 'Обновление моделей карттриджей',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateInventory',
        'type' => '2',
        'description' => 'Обновление Инвентарных номеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateLoading',
        'type' => '2',
        'description' => 'Обновление заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateLoadingReport',
        'type' => '2',
        'description' => 'Обновление отчетов заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateOrder',
        'type' => '2',
        'description' => 'Обновление заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updatePrinter',
        'type' => '2',
        'description' => 'Обновление картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updatePrinterCartridgeCompatiblity',
        'type' => '2',
        'description' => 'Обновление совместимости моделей картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updatePrinterModels',
        'type' => '2',
        'description' => 'Обновление моделей принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'updateUserOrder',
        'type' => '2',
        'description' => 'Обновление заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'user',
        'type' => '1',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewCartridge',
        'type' => '2',
        'description' => 'Просмотр картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewCartridgeLoading',
        'type' => '2',
        'description' => 'Просмотр заправок Картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewCartridgeModels',
        'type' => '2',
        'description' => 'Просмотр моделей карттриджей',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewInventory',
        'type' => '2',
        'description' => 'Просмотр Инвентарных номеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewLoading',
        'type' => '2',
        'description' => 'Просмотр заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewLoadingReport',
        'type' => '2',
        'description' => 'Просмотр отчетов заправок',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewOrder',
        'type' => '2',
        'description' => 'Просмотр заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewPrinter',
        'type' => '2',
        'description' => 'Просмотр картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewPrinterCartridgeCompatiblity',
        'type' => '2',
        'description' => 'Просмотр совместимости моделей картриджей и принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewPrinterModels',
        'type' => '2',
        'description' => 'Просмотр моделей принтеров',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
    [
        'name' => 'viewUserOrder',
        'type' => '2',
        'description' => 'Просмотр заявок на замену/установку картриджа',
        'rule_name' => null,
        'data' => null,
        'created_at' => '1551183513',
        'updated_at' => '1551183513',
    ],
]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%auth_item}} CASCADE');
    }
}
